# ===================================================================
# Local CI specific properties: this file will only be loaded during startup if the profile localci is active
#
# This configuration overrides the application.yml file.
# ===================================================================
artemis:
    continuous-integration:
        # The number of threads that are used to execute the CI jobs.
        thread-pool-size: 1
        # If true, the CI jobs will be executed asynchronously. If false, the CI jobs will be executed synchronously (e.g. for debugging and tests).
        asynchronous: true
        # The maximum number of seconds that a CI job is allowed to run. If the job exceeds this time, it will be terminated.
        timeout-seconds: 60
        # The number of builds that can be added to the local CI queue per second. This can prevent the CI system from being overloaded on slow machines.
        rate-limit: 1
