# ----------------------------------------------------------------------------------------------------------------------
# Artemis-Prod-MySQL Setup
# ----------------------------------------------------------------------------------------------------------------------
# this is the default artemis production setup also linked to in the docker-compose.yml in the project root
services:
    artemis:
        extends:
            file: ./artemis.yml
            service: artemis
        depends_on:
            mysql:
                condition: service_healthy
        # restart: on-failure:3
        restart: always

        # volumes:
        #     - ./.docker-data/artemis-data:/opt/artemis/data

    mysql:
        extends:
            file: ./mysql.yml
            service: mysql
        # restart: on-failure:3
        restart: always
        # volumes:
        #     - ./.docker-data/artemis-mysql-data:/var/lib/mysql

    nginx:
        extends:
            file: ./nginx.yml
            service: nginx
        # the artemis-app service needs to be started, otherwise there are problems with name resolution in docker
        depends_on:
            artemis:
                condition: service_started
        restart: always
        # restart: on-failure:3

networks:
    artemis:
        driver: bridge
        name: artemis

volumes:
    artemis-data:
        name: artemis-data
    artemis-mysql-data:
        name: artemis-mysql-data