# ----------------------------------------------------------------------------------------------------------------------
# GitLabCI base service
# ----------------------------------------------------------------------------------------------------------------------

services:
    gitlab-runner:
        image: docker.io/gitlab/gitlab-runner:latest
        pull_policy: always
        container_name: artemis-gitlab-runner
        platform: linux/amd64
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /usr/local/bin/docker:/usr/bin/docker
          - artemis-gitlabci-runner-config:/etc/gitlab-runner
          - ./nginx/certs/rootCA.pem:/etc/gitlab-runner/certs/gitlab.artemis.hs-merseburg.de.crt
          - ./nginx/certs/rootCA.pem:/etc/gitlab-runner/certs/artemis.hs-merseburg.de.crt
          - ./nginx/certs/rootCA.pem:/etc/gitlab/trusted-certs/gitlab.artemis.hs-merseburg.de.crt
        networks:
            - artemis
        hostname: gitlab-runner.artemis

networks:
    artemis:
        name: artemis
        driver: bridge

volumes:
    artemis-gitlabci-runner-config:
        name: artemis-gitlabci-runner-config