# ----------------------------------------------------------------------------------------------------------------------
# GitLab-GitLabCI Setup
# ----------------------------------------------------------------------------------------------------------------------

services:
  gitlab:
    # TODO: check if more settings can also be integrated into gitlab.yml
    extends:
      file: ./gitlab.yml
      service: gitlab
    restart: always
    volumes:
      - artemis-gitlab-data:/var/opt/gitlab
      - artemis-gitlab-logs:/var/log/gitlab
      - artemis-gitlab-config:/etc/gitlab
      - ./gitlab/setup.sh:/setup.sh
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "${GIT_SERVER_NAME}"
        prometheus_monitoring['enable'] = false
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        gitlab_rails['monitoring_whitelist'] = ['0.0.0.0/0']
        nginx['redirect_http_to_https'] = true
        nginx['redirect_http_to_https_port'] = 80
        letsencrypt['enable'] = ${SSL_ENABLED}
        letsencrypt['auto_renew_hour'] = "12"
        letsencrypt['auto_renew_minute'] = "30"
        letsencrypt['auto_renew_day_of_month'] = "*/7"
    env_file:
      - ./gitlab/gitlab-gitlabci.env
    shm_size: "256m"

  gitlab-runner:
    extends:
      file: ./gitlabci.yml
      service: gitlab-runner
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/bin/docker
      - artemis-gitlabci-runner-config:/etc/gitlab-runner
      - ./gitlab/register.sh:/register.sh
    env_file:
      - ./gitlab/gitlab-gitlabci.env

networks:
    artemis:
        name: artemis
        driver: bridge

volumes:
  artemis-gitlab-data:
    name: artemis-gitlab-data
  artemis-gitlab-logs:
    name: artemis-gitlab-logs
  artemis-gitlab-config:
    name: artemis-gitlab-config
  artemis-gitlabci-runner-config:
    name: artemis-gitlabci-runner-config
