services:
    gitlab:
        container_name: artemis-gitlab
        build: ./gitlab
        platform: linux/amd64
        pull_policy: build
        volumes:
            - artemis-gitlab-data:/var/opt/gitlab
            - artemis-gitlab-logs:/var/log/gitlab
            - artemis-gitlab-config:/etc/gitlab
            - ./gitlab/setup.sh:/setup.sh
            - ./nginx/certs/rootCA.pem:/etc/gitlab/trusted-certs/artemis.hs-merseburg.de.crt
            - ./nginx/certs/rootCA.pem:/etc/gitlab/trusted-certs/gitlab.artemis.hs-merseburg.de.crt
        environment:
            GITLAB_OMNIBUS_CONFIG: "prometheus_monitoring['enable'] = false; gitlab_rails['gitlab_shell_ssh_port'] = 2222; gitlab_rails['monitoring_whitelist'] = ['0.0.0.0/0']"
            GITLAB_ROOT_PASSWORD:
        ports:
            - "2222:22"
            - "8081:80"
        # expose the ports to make them reachable docker internally even if the external port mapping changes
        expose:
            - "22"
            - "80"
        hostname: gitlab.artemis
        networks:
            - artemis
        extra_hosts:
            - "host.docker.internal:host-gateway"
            - "artemis.hs-merseburg.de:host-gateway"
            - "gitlab.artemis.hs-merseburg.de:host-gateway"
networks:
    artemis:
        driver: "bridge"
        name: artemis

volumes:
    artemis-gitlab-data:
        name: artemis-gitlab-data
    artemis-gitlab-logs:
        name: artemis-gitlab-logs
    artemis-gitlab-config:
        name: artemis-gitlab-config
