stages:
    - test
    - upload

test-job:
    image: ${ARTEMIS_BUILD_DOCKER_IMAGE}
    stage: test
    only:
        variables:
            - $CI_COMMIT_BRANCH == $ARTEMIS_SUBMISSION_GIT_BRANCH
    allow_failure: true
    variables:
        GIT_STRATEGY: none
        MAVEN_OPTS: -Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.dateTimeFormat=[yyyy-MM-dd'T'HH:mm:ssX] -Dorg.slf4j.simpleLogger.logFile=${ARTEMIS_BUILD_LOGS_FILE}
    before_script:
        - set -o pipefail
        - git config --global http.sslCAInfo ${CI_SERVER_TLS_CA_FILE}
    script:
        - git clone --branch ${ARTEMIS_TEST_GIT_BRANCH} ${CI_SERVER_PROTOCOL}://${ARTEMIS_TEST_GIT_USER}:${ARTEMIS_TEST_GIT_TOKEN}@${CI_SERVER_HOST}:${CI_SERVER_PORT}/${CI_PROJECT_NAMESPACE}/${ARTEMIS_TEST_GIT_REPOSITORY_SLUG} .
        - git clone --branch ${ARTEMIS_SUBMISSION_GIT_BRANCH} ${CI_SERVER_PROTOCOL}://${ARTEMIS_TEST_GIT_USER}:${ARTEMIS_TEST_GIT_TOKEN}@${CI_SERVER_HOST}:${CI_SERVER_PORT}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME} assignment
        - export ARTEMIS_NOTIFICATION_SECRET=[hidden] # Workaround for overwriting the secret
        - export ARTEMIS_TEST_GIT_TOKEN=[hidden]
        - ( mvn clean test -B --fail-at-end && ARTEMIS_BUILD_STATUS="success" || ARTEMIS_BUILD_STATUS="failed" ) | tee ${ARTEMIS_BUILD_LOGS_FILE}
    after_script:
        - echo "ARTEMIS_BUILD_STATUS=${ARTEMIS_BUILD_STATUS}" >> .env
        - echo "ARTEMIS_TEST_GIT_HASH=$(git rev-parse HEAD)" >> .env
        - echo "ARTEMIS_SUBMISSION_GIT_HASH=${CI_COMMIT_SHA}" >> .env
        - echo "ARTEMIS_SUBMISSION_GIT_REPOSITORY_SLUG=${CI_PROJECT_NAME}" >> .env
        # FIXME: FILTERING DOES NOT WORK WITH NEWER SYSTEM!
        - sed '0,/^\[.*\] \[INFO\] Results:$/d' ${ARTEMIS_BUILD_LOGS_FILE} > ${ARTEMIS_BUILD_LOGS_FILE}.tmp # Remove unused leading logs
        - sed 's/\(.*\) \[ERROR\]   \(.*Test\)[>.]\(.*:\)[0-9]*\(.*\)/\1 \[ERROR\] [\2\]:\4/p' ${ARTEMIS_BUILD_LOGS_FILE}.tmp > ${ARTEMIS_BUILD_LOGS_FILE}.tmp2 # Reformat Failed Tests
        - sed '/^\[.*\] \[INFO\] BUILD \(.*\)$/q' ${ARTEMIS_BUILD_LOGS_FILE}.tmp2 >> ${ARTEMIS_BUILD_LOGS_FILE} # Remove unsed trailing logs
        - mkdir -p ${ARTEMIS_TEST_RESULTS_DIR} # incase the parent directories do not exist
        - mv target/surefire-reports/* ${ARTEMIS_TEST_RESULTS_DIR}
    artifacts:
        paths:
            - ${ARTEMIS_BUILD_LOGS_FILE}
            - ${ARTEMIS_TEST_RESULTS_DIR}/*.xml
        reports:
            dotenv: .env

upload-job:
    image: ${ARTEMIS_NOTIFICATION_PLUGIN_DOCKER_IMAGE}
    stage: upload
    dependencies:
        - test-job
    only:
        variables:
            - $CI_COMMIT_BRANCH == $ARTEMIS_SUBMISSION_GIT_BRANCH
    variables:
        GIT_STRATEGY: none
    before_script:
        - keytool -import -trustcacerts -storepass changeit -alias root -file ${CI_SERVER_TLS_CA_FILE} -keystore $JAVA_HOME/jre/lib/security/cacerts -noprompt
    script:
        - cp -r /notification-plugin/* .
        - gradle run
